### ISSUE TITLE
No able to find blocks mining with x11 algo 

### ISSUE THREAD

**Issue by mario1987** [vagabondan/CoiniumServ#17] opened 2017-08-23 14:32 UTC
Made this issue instead of https://github.com/bonesoul/CoiniumServ/issues/837 which in not on finding no blocks 

@vagabondan As I am thinking now the coin that I am mining does not use SIGWIT as LTC does maybe that is the problem. The logs that I am going to upload now is from the standard cs

Coin Wallet with found block
[CoinWallet-debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1245756/CoinWallet-debug.TXT)

CS Logs of standard CoiniumServ not recognizing and displaying the found block
[Standard-CS-debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1245757/Standard-CS-debug.TXT)
[Standard-CS-packet-20170823.TXT](https://github.com/vagabondan/CoiniumServ/files/1245758/Standard-CS-packet-20170823.TXT)
[Standard-CS-server.TXT](https://github.com/vagabondan/CoiniumServ/files/1245759/Standard-CS-server.TXT)

**Comment by vagabondan** [comment] 2017-08-23 15:38
@mario1987 as I wrote earlier https://github.com/bonesoul/CoiniumServ/issues/837#issuecomment-324231909 the problem is with your proof-of-work function: it produces too large hash, twice larger than it should be. So, I asked you to show me your config/coins/reddbytecoin.json because it is absent in this repository.

**P.S.**
As I saw in your packet.log there is proof of stake part for this coin. I'll check the appropriate code section.

**Comment by mario1987** [comment] 2017-08-23 16:24
@vagabondan  That kind of weird because when I use the same config files In the standard CS I am finding blocks so the POW function works but not with this version and I did not changed any thing in the src I only downloaded and build it.  

Yes there is a POS but I disabled it. In the coins config file  I will include that one to then 


This is the coin config json file in the pool folder of CS
[reddbyteCoin.TXT](https://github.com/vagabondan/CoiniumServ/files/1246349/reddbyteCoin.TXT)


This config file in in the coins folder of CS
[reddbytecoin.TXT](https://github.com/vagabondan/CoiniumServ/files/1246149/reddbytecoin.TXT)

This is the file of the deamon config in AppData folder
[AppData-ReddByte.TXT](https://github.com/vagabondan/CoiniumServ/files/1246177/AppData-ReddByte.TXT)

**Comment by vagabondan** [comment] 2017-08-23 18:00
@mario1987 Excuse me if I'm wrong and missed something important, but I haven't found the log where it was stated that you had found the block. Only such messages appears:

`We thought a block was found but it was rejected by the coin daemon; [2aca6279fe7c7e5abee7376cdb44ffaa71bf706912471eb7556c6546de247b31] - reason; Block not found
`
But this is the consequence of the incorrect conversion of byte array into big SIGNED integer. Nearly one half of all shares are became negative big integers during incorrect conversion and generate false positive triggering being compared with targets.
Here is my fix for this bug: 
https://github.com/vagabondan/CoiniumServ/commit/89b448cdad0627557546eb1de8e6e6be6a40a588#diff-eb8c3ff8516f5e586fec335ab34e8702

If I'm wrong, please, point to message that reads about block generated by CS is accepted.

I believe that real root cause of this problem is incorrect conversion of target into BIGUINT32 while it should be converted into BIGUINT64 actually for RBC.

**Comment by mario1987** [comment] 2017-08-23 18:40
Those config files are from the standard CS  not your version.  and yes i found blocks with it even if it says  

We thought a block was found but it was rejected by the coin daemon; [2aca6279fe7c7e5abee7376cdb44ffaa71bf706912471eb7556c6546de247b31] - reason; Block not found

This is proof of the latest block that I have found with the Standard CS
![block-found-proof](https://user-images.githubusercontent.com/5938706/29631460-fd32b780-883f-11e7-80c8-9f112b69d6b1.jpg)

NotifyTransactionChanged e7e0c400489792f27af2b3f23c4409778bc37651ceb15e076c3d4200ac53e152 status=1
ProcessBlock: ACCEPTED
updateWallet e7e0c400489792f27af2b3f23c4409778bc37651ceb15e076c3d4200ac53e152 1

The block found in the pic can be found in the Wallet log with  bonesoul  version.

note that this in with the version of  bonesoul not your version  with your version I don't get that and also not finding any blocks  

I think i will gather all logs in to 1 comment to avoid confusion so it will be complete 


Coin's config file for both versions is the same

[reddbyteCoin.TXT](https://github.com/vagabondan/CoiniumServ/files/1246574/reddbyteCoin.TXT)
[reddbytecoin.TXT](https://github.com/vagabondan/CoiniumServ/files/1246575/reddbytecoin.TXT)
[AppData-ReddByte.TXT](https://github.com/vagabondan/CoiniumServ/files/1246579/AppData-ReddByte.TXT)


bonesoul  CS version 

[Standard-CS-server.TXT](https://github.com/vagabondan/CoiniumServ/files/1246538/Standard-CS-server.TXT)
[Standard-CS-packet-20170823.TXT](https://github.com/vagabondan/CoiniumServ/files/1246539/Standard-CS-packet-20170823.TXT)
[Standard-CS-debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1246542/Standard-CS-debug.TXT)

Wallet Debug Log with this version
[CoinWallet-debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1246578/CoinWallet-debug.TXT)


vagabondan CS version 

[CS-server.TXT](https://github.com/vagabondan/CoiniumServ/files/1246570/CS-server.TXT)
[CS-packet-20170823.TXT](https://github.com/vagabondan/CoiniumServ/files/1246571/CS-packet-20170823.TXT)
[CS-debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1246572/CS-debug.TXT)

Wallet Debug Log with this version 
[Wallet-debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1246573/Wallet-debug.TXT)

The version that I want to use is vagabondan version. So your version but the problem that I am facing is I am not finding any blocks with it. The logs of the bonesoul version was only to show that I was able to find blocks with the coin config can been seen in the pic not for solving problems that the version have.

Your version is giving me a POW function problem as you said "@mario1987 Thank you! Something is definetly wrong with Proof Of Work function:
POW: 6b33f25bf896d6b102ae236f6c055e63f33b3e24f3320e74b8def9640681880ef1e4a3b75b677aa75770d2e9c23157dcd463ef35bed26db6b9d538161fc0a48d
TGT: 128e8400000000000000000000000000000000000000000000000000" 

This is my main problem because if the POW function is not working I am not going to find any blocks.

**Comment by vagabondan** [comment] 2017-08-23 21:19
Ok, I believe, I know what's going on:)
I will create special branch for you with some special modification. Please, download it, compile and run. If I'm right, you will get blocks twice faster than in bonesoul version.
Ok?

**Comment by mario1987** [comment] 2017-08-23 21:33
@vagabondan  Ok that would be great. I really appreciate it. But I am not planning to online mine x11 algo's  also the other ones which is stated for CS.

again I really appreciate it tnx for the hard work.

**Comment by mario1987** [comment] 2017-08-23 21:38
I downloaded it and going to test it soon tnx again.

**Comment by vagabondan** [comment] 2017-08-23 21:38
@mario1987 It's just an attempt. I hope it will help.
https://github.com/vagabondan/CoiniumServ/tree/mario-x11-special_edition

**Comment by mario1987** [comment] 2017-08-23 22:02
@vagabondan I have not found any blocks yet but I have some debug log's I will run the miner on the pool for the night. If i find a block I will let you know.

Here are the log's till now.  


[debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1247169/debug.TXT)
[packet-20170823.TXT](https://github.com/vagabondan/CoiniumServ/files/1247171/packet-20170823.TXT)
[server.TXT](https://github.com/vagabondan/CoiniumServ/files/1247172/server.TXT)
[debug With CS X11.TXT](https://github.com/vagabondan/CoiniumServ/files/1247195/debug.With.CS.X11.TXT)

**Comment by vagabondan** [comment] 2017-08-23 22:11
@mario1987 Did you download this branch?:
https://github.com/vagabondan/CoiniumServ/tree/mario-x11-special_edition
You should use exactly this one. Please check, that you have latest commits changes for this branch.

You should see the following phrase in debug.log:
"Job.Target is greater than or equal HeaderValue"
and much more additional output.

**Comment by mario1987** [comment] 2017-08-23 22:20
@vagabondan  Yes i did

**Comment by vagabondan** [comment] 2017-08-23 22:20
@mario1987 But I don't see this phrase in your log.

**Comment by mario1987** [comment] 2017-08-23 22:22
![naamloos](https://user-images.githubusercontent.com/5938706/29641095-43573b92-8862-11e7-970a-d5cf77ed9d41.jpg)

**Comment by vagabondan** [comment] 2017-08-23 22:23
@mario1987 Please download once again, I think you've done it before my last commits.

**Comment by mario1987** [comment] 2017-08-23 22:25
Ok

**Comment by mario1987** [comment] 2017-08-23 22:43
@vagabondan I have downloaded and compiled the special version but I am getting a lot of rejections.

[debug.TXT](https://github.com/vagabondan/CoiniumServ/files/1247249/debug.TXT)
[debugCS.TXT](https://github.com/vagabondan/CoiniumServ/files/1247250/debugCS.TXT)
[packet-20170824.TXT](https://github.com/vagabondan/CoiniumServ/files/1247251/packet-20170824.TXT)
[server.TXT](https://github.com/vagabondan/CoiniumServ/files/1247252/server.TXT)

**Comment by mario1987** [comment] 2017-08-23 22:46
@vagabondan   I also get this when compiling 

1>------ Build started: Project: CoiniumServ, Configuration: Debug Any CPU ------
1>C:\Users\Mario\Desktop\Nieuwe map (10)\CoiniumServ-mario-x11-special_edition\src\CoiniumServ\Overpool\OverpoolClient.cs(100,4,100,7): warning CS0162: Unreachable code detected
1>C:\Users\Mario\Desktop\Nieuwe map (10)\CoiniumServ-mario-x11-special_edition\src\CoiniumServ\Overpool\OverpoolClient.cs(117,4,117,6): warning CS0162: Unreachable code detected
1>C:\Users\Mario\Desktop\Nieuwe map (10)\CoiniumServ-mario-x11-special_edition\src\CoiniumServ\Shares\Share.cs(244,17,244,33): warning CS0162: Unreachable code detected
1>  CoiniumServ -> C:\Users\Mario\Desktop\Nieuwe map (10)\CoiniumServ-mario-x11-special_edition\bin\Debug\CoiniumServ.exe
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by vagabondan** [comment] 2017-08-23 22:47
@mario1987 Ok, it's normal. Set miners' difficulty at network level and switch off vardiff. This should reduce false-positive triggering

**Comment by mario1987** [comment] 2017-08-23 22:48
@vagabondan   I have found a block but it is not registered at the CS web as pending block

**Comment by vagabondan** [comment] 2017-08-23 22:50
@mario1987 Good! Implement recommendations from https://github.com/vagabondan/CoiniumServ/issues/17#issuecomment-324484092 and you will get less errors.

**Comment by vagabondan** [comment] 2017-08-23 22:54
@mario1987 what is in logs for that block?

**Comment by mario1987** [comment] 2017-08-23 22:56
@vagabondan  Ok I will do that in a sec.
No that I have found a block I see that the payments is not done. Also  the found block is not registered as CS. 

![naamloos](https://user-images.githubusercontent.com/5938706/29642088-0d075356-8867-11e7-9167-4c4f5682bfb0.jpg)

**Comment by vagabondan** [comment] 2017-08-23 23:00
@mario1987 This is because you need to actualize links in you reddbytecoin.json I believe. CS just can't get info from web servers.
So is block really found and left screen says it's in pending status now?

**Comment by mario1987** [comment] 2017-08-23 23:03
@vagabondan  And how do i do that?  Is that in the pool json of coin json ? and what links do I need

**Comment by mario1987** [comment] 2017-08-23 23:04
@vagabondan because I cant find anything in the guide of CS for that on how to do it or I am missing something.

**Comment by vagabondan** [comment] 2017-08-23 23:09
@mario1987 send me your debug.log to look at. 
You need to modify .../bin/Debug/config/coin/reddbytecoin.json
Here it is:

```
{
    "name": "ReddByte",
    "symbol": "RBC",
    "algorithm": "x11",
    "site": "https://bitcointalk.org/index.php?topic=1737799.0;all",
	
    "blockExplorer": {
        "block": "https://chainz.cryptoid.info/rbc/block/",
        "tx": "https://chainz.cryptoid.info/rbc/tx/",
        "address": "https://chainz.cryptoid.info/rbc/address/"
    }

}
```

Try to use these links. Maybe they are correct. Also check that your redis server is running and your pool configuration file has correct requisites.

**Comment by vagabondan** [comment] 2017-08-23 23:10
@mario1987 links are no longer actual. They have got changed formats... You need find blockexploprers sites that accepts http get requests like http://<blockexplorer_site>/rbc/blocks/<block_hash> for example

And check your redis connection.

**Comment by mario1987** [comment] 2017-08-23 23:16
@vagabondan Its making a connection  on the CS it says  [CoiniumServ.Persistance.Providers.Redis.RedisProvider] [ReddByte] Redis storage initialized: 212.168.1.213:50580, v{2:l}.

**Comment by vagabondan** [comment] 2017-08-23 23:24
Oh, I see you're mining well, so my mission is accomplished:) Good dreams ;)
![image](https://user-images.githubusercontent.com/2213110/29642747-4d1428fa-8873-11e7-83f0-663939e92ce5.png)

**Comment by mario1987** [comment] 2017-08-23 23:27
Yes the mining is accomplished now to get CS seeing blocks pending and payouts  tnx by the way

**Comment by vagabondan** [comment] 2017-08-23 23:28
@mario1987 look at your debug.log to get the answer.

**Comment by mario1987** [comment] 2017-08-23 23:31
@vagabondan  I am using redis on the same system as pool will see how it goes

**Comment by mario1987** [comment] 2017-08-24 00:23
@vagabondan  I have done so but not finding anything.  the thing that I did found was in the CS API  /api/pool/{coin}  I found this   
"blocks": {
    "pending": 0,
    "confirmed": 0,
    "orphaned": 0,
    "total": 0,
    "latest": [],
    "latestPaid": []
  }

I think I am missing something but don't know what

**Comment by vagabondan** [comment] 2017-08-24 05:17
@mario1987 You are missing to check debug.log

**Comment by mario1987** [comment] 2017-08-24 13:11
@vagabondan  I already checked the debug.log. But i will check it again. And this issue can be closed it is solved. tnx

**Closed as completed** 2017-08-24 18:05 UTC

**Comment by Virtuworks** [comment] 2017-08-27 14:43
Guys - your problem here is missing support for Masternodes here is a sample implementation I've solved this issue with the following process: 

https://github.com/dashpay/node-stratum-pool/pull/1

**Comment by loutchano** [comment] 2017-08-27 17:55
i have this problem with all gpu algoritms x11 keccak nist5 etc

my miner send shares bud my coinium sais 

shares rejected 0.00/100 low dificulty .. 

i have try change start diff bud nothing any solution ??? 

thanks  and sorry for my bad english
